export const Themes = {
  ReservoirDogs: 'reservoir',
  PulpFiction: 'pulp',
  KillBillVol1: 'killbill1',
  KillBillVol2: 'killbill2',
  JackieBrown: 'jackie',
  DeathProof: 'deathproof',
  InglouriousBasterds: 'basterds',
  DjangoUnchained: 'django',
  TheHatefulEight: 'hateful',
  OnceUponATimeInHollywood: 'hollywood',
} as const

export type ThemeName = (typeof Themes)[keyof typeof Themes]

export const themeConfig = {
  [Themes.ReservoirDogs]: {
    name: 'Reservoir Dogs',
    primary: 'bg-reservoir-dark',
    text: 'text-reservoir-light',
    accent: 'bg-reservoir-primary',
    card: 'bg-reservoir-secondary',
    secondary: 'bg-reservoir-accent',
    muted: 'bg-reservoir-muted',
    highlight: 'bg-reservoir-pink',
  },
  [Themes.PulpFiction]: {
    name: 'Pulp Fiction',
    primary: 'bg-pulp-primary',
    text: 'text-pulp-secondary',
    accent: 'bg-pulp-red',
    card: 'bg-pulp-yellow',
    secondary: 'bg-pulp-accent',
    muted: 'bg-pulp-blue',
    highlight: 'bg-pulp-cyan',
  },
  [Themes.KillBillVol1]: {
    name: 'Kill Bill Vol.1',
    primary: 'bg-killbill1-dark',
    text: 'text-killbill1-lime',
    accent: 'bg-killbill1-primary',
    card: 'bg-killbill1-secondary',
    secondary: 'bg-killbill1-accent',
    muted: 'bg-killbill1-muted',
    highlight: 'bg-killbill1-green',
  },
  [Themes.KillBillVol2]: {
    name: 'Kill Bill Vol.2',
    primary: 'bg-killbill2-dark',
    text: 'text-killbill2-secondary',
    accent: 'bg-killbill2-primary',
    card: 'bg-killbill2-muted',
    secondary: 'bg-killbill2-accent',
    muted: 'bg-killbill2-muted',
    highlight: 'bg-killbill2-secondary',
  },
  [Themes.JackieBrown]: {
    name: 'Jackie Brown',
    primary: 'bg-jackie-dark',
    text: 'text-jackie-secondary',
    accent: 'bg-jackie-red',
    card: 'bg-jackie-gold',
    secondary: 'bg-jackie-primary',
    muted: 'bg-jackie-muted',
    highlight: 'bg-jackie-accent',
  },
  [Themes.DeathProof]: {
    name: 'Death Proof',
    primary: 'bg-deathproof-primary',
    text: 'text-deathproof-light',
    accent: 'bg-deathproof-accent',
    card: 'bg-deathproof-pink',
    secondary: 'bg-deathproof-secondary',
    muted: 'bg-deathproof-muted',
    highlight: 'bg-deathproof-brown',
  },
  [Themes.InglouriousBasterds]: {
    name: 'Inglourious Basterds',
    primary: 'bg-basterds-secondary',
    text: 'text-basterds-green',
    accent: 'bg-basterds-primary',
    card: 'bg-basterds-muted',
    secondary: 'bg-basterds-accent',
    muted: 'bg-basterds-muted',
    highlight: 'bg-basterds-gray',
  },
  [Themes.DjangoUnchained]: {
    name: 'Django Unchained',
    primary: 'bg-django-dark',
    text: 'text-django-secondary',
    accent: 'bg-django-accent',
    card: 'bg-django-blue',
    secondary: 'bg-django-primary',
    muted: 'bg-django-primary',
    highlight: 'bg-django-blue',
  },
  [Themes.TheHatefulEight]: {
    name: 'The Hateful Eight',
    primary: 'bg-hateful-primary',
    text: 'text-hateful-muted',
    accent: 'bg-hateful-red',
    card: 'bg-hateful-gold',
    secondary: 'bg-hateful-secondary',
    muted: 'bg-hateful-accent',
    highlight: 'bg-hateful-yellow',
  },
  [Themes.OnceUponATimeInHollywood]: {
    name: 'Once Upon a Time in Hollywood',
    primary: 'bg-hollywood-primary',
    text: 'text-hollywood-gold',
    accent: 'bg-hollywood-purple',
    card: 'bg-hollywood-pink',
    secondary: 'bg-hollywood-secondary',
    muted: 'bg-hollywood-muted',
    highlight: 'bg-hollywood-red',
  },
} as const
